Repository PLUB2022/PLUB-Server, pull requests merged in 2023-01, with the labels that each got.

#33 [PLUB-123] 홈 화면 관련 기능 구현, 카테고리 개선
  build.gradle
  src/main/java/plub/plubserver/config/querydsl/QuerydslConfig.java
  src/main/java/plub/plubserver/config/security/SecurityConfig.java
  src/main/java/plub/plubserver/domain/account/controller/AccountController.java
  src/main/java/plub/plubserver/domain/account/dto/AccountDto.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/model/AccountCategory.java
  src/main/java/plub/plubserver/domain/account/repository/AccountCategoryRepository.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
  src/main/java/plub/plubserver/domain/account/service/AuthService.java
  src/main/java/plub/plubserver/domain/category/controller/CategoryController.java
  src/main/java/plub/plubserver/domain/category/dto/CategoryDto.java
  src/main/java/plub/plubserver/domain/category/model/SubCategory.java
  src/main/java/plub/plubserver/domain/category/service/CategoryService.java
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/dto/PlubbingDto.java
  src/main/java/plub/plubserver/domain/plubbing/model/Plubbing.java
  src/main/java/plub/plubserver/domain/plubbing/repository/AccountPlubbingRepository.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepository.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryCustom.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryImpl.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
Labels: 기능, 리펙토링, 리뷰 피드백 진행 중

#34 [PLUB-121] 모집 기능 구현 (지원, 상세 조회, 호스트)
  src/main/java/plub/plubserver/common/exception/CommonErrorCode.java
  src/main/java/plub/plubserver/common/exception/GlobalExceptionHandler.java
  src/main/java/plub/plubserver/domain/account/config/AccountCode.java
  src/main/java/plub/plubserver/domain/account/config/AuthCode.java
  src/main/java/plub/plubserver/domain/account/exception/AccountExceptionHandler.java
  src/main/java/plub/plubserver/domain/account/exception/AuthExceptionHandler.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/category/config/CategoryCode.java
  src/main/java/plub/plubserver/domain/category/exception/CategoryExceptionHandler.java
  src/main/java/plub/plubserver/domain/category/service/CategoryService.java
  src/main/java/plub/plubserver/domain/plubbing/config/PlubbingCode.java
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/dto/PlubbingDto.java
  src/main/java/plub/plubserver/domain/plubbing/exception/PlubbingExceptionHandler.java
  src/main/java/plub/plubserver/domain/plubbing/model/AccountPlubbing.java
  src/main/java/plub/plubserver/domain/plubbing/model/Plubbing.java
  src/main/java/plub/plubserver/domain/plubbing/repository/AccountPlubbingRepository.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryImpl.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/config/RecruitCode.java
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/dto/RecruitDto.java
  src/main/java/plub/plubserver/domain/recruit/exception/RecruitException.java
  src/main/java/plub/plubserver/domain/recruit/exception/RecruitExceptionHandler.java
  src/main/java/plub/plubserver/domain/recruit/model/AccountRecruit.java
  src/main/java/plub/plubserver/domain/recruit/model/ApplicantStatus.java
  src/main/java/plub/plubserver/domain/recruit/model/AppliedAccount.java
  src/main/java/plub/plubserver/domain/recruit/model/Recruit.java
  src/main/java/plub/plubserver/domain/recruit/model/RecruitQuestion.java
  src/main/java/plub/plubserver/domain/recruit/model/RecruitQuestionAnswer.java
  src/main/java/plub/plubserver/domain/recruit/repository/AppliedAccountRepository.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitQuestionRepository.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepository.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/main/java/plub/plubserver/util/BuildTest.java
  src/main/resources/application.yml
  src/test/java/plub/plubserver/domain/plubbing/PlubbingMockUtils.java
  src/test/java/plub/plubserver/domain/plubbing/PlubbingServiceTest.java
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceBootTest.java
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceMockTest.java
  temp/test.txt
Labels: 기능

#35 [PLUB-118] plubbing 관련 리팩토링
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/dto/PlubbingDto.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/resources/application.yml
Labels: 리펙토링, 리뷰 피드백 진행 중

#36 [PLUB-125] 모집 API 리팩토링, 호스트 모집 수정 구현
  src/main/java/plub/plubserver/domain/account/exception/AccountExceptionHandler.java
  src/main/java/plub/plubserver/domain/account/exception/AuthExceptionHandler.java
  src/main/java/plub/plubserver/domain/category/exception/CategoryExceptionHandler.java
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/dto/PlubbingDto.java
  src/main/java/plub/plubserver/domain/plubbing/exception/PlubbingExceptionHandler.java
  src/main/java/plub/plubserver/domain/plubbing/model/AccountPlubbing.java
  src/main/java/plub/plubserver/domain/plubbing/model/MeetingDay.java
  src/main/java/plub/plubserver/domain/plubbing/model/Plubbing.java
  src/main/java/plub/plubserver/domain/plubbing/model/PlubbingMeetingDay.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/config/RecruitCode.java
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/dto/RecruitDto.java
  src/main/java/plub/plubserver/domain/recruit/exception/RecruitExceptionHandler.java
  src/main/java/plub/plubserver/domain/recruit/model/Recruit.java
  src/main/java/plub/plubserver/domain/recruit/model/RecruitStatus.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepository.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/test/java/plub/plubserver/domain/plubbing/PlubbingMockUtils.java
  src/test/java/plub/plubserver/domain/plubbing/PlubbingServiceTest.java
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceBootTest.java
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceMockTest.java
Labels: 기능, 리팩토링

#37 [PLUB-125] 모집 북마크, 검색 구현
  src/main/java/plub/plubserver/common/dummy/AdminCategoryDummy.java
  src/main/java/plub/plubserver/common/dummy/PlubbingRecruitDummy.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryImpl.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/dto/QuestionDto.java
  src/main/java/plub/plubserver/domain/recruit/dto/RecruitDto.java
  src/main/java/plub/plubserver/domain/recruit/model/Bookmark.java
  src/main/java/plub/plubserver/domain/recruit/repository/BookmarkRepository.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepository.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepositoryCustom.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepositoryImpl.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/main/resources/application.yml
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceTest.java
Labels: 기능

#39 [PLUB-134] Static Response Controller 제작 (게시판, 공지)
  src/main/java/plub/plubserver/common/dto/CommentDto.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/comment/model/Comment.java
  src/main/java/plub/plubserver/domain/feed/controller/PlubbingFeedController.java
  src/main/java/plub/plubserver/domain/feed/dto/PlubbingFeedDto.java
  src/main/java/plub/plubserver/domain/feed/model/FeedType.java
  src/main/java/plub/plubserver/domain/feed/model/PlubbingFeed.java
  src/main/java/plub/plubserver/domain/feed/model/PlubbingFeedImage.java
  src/main/java/plub/plubserver/domain/feed/repository/PlubbingFeedRepository.java
  src/main/java/plub/plubserver/domain/feed/service/PlubbingFeedService.java
  src/main/java/plub/plubserver/domain/plubbing/model/AccountPlubbing.java
  src/main/java/plub/plubserver/domain/plubbing/model/Plubbing.java
  src/main/java/plub/plubserver/domain/todo/model/PlubbingTodo.java
  src/main/java/plub/plubserver/notice/controller/PlubbingNoticeController.java
  src/main/java/plub/plubserver/notice/dto/PlubbingNoticeDto.java
  src/main/java/plub/plubserver/notice/model/PlubbingNotice.java
  src/main/java/plub/plubserver/notice/repository/PlubbingNoticeRepository.java
  src/main/java/plub/plubserver/notice/service/PlubbingNoticeService.java
Labels: 기능

#40 [PLUB-135] Static Response Controller 제작 (알림, 아카이브)
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/alarm/model/AlarmType.java
  src/main/java/plub/plubserver/domain/archive/controller/PlubbingArchiveController.java
  src/main/java/plub/plubserver/domain/archive/dto/PlubbingArchiveDto.java
  src/main/java/plub/plubserver/domain/archive/model/PlubbingArchive.java
  src/main/java/plub/plubserver/domain/archive/model/PlubbingArchiveImage.java
  src/main/java/plub/plubserver/domain/archive/repository/PlubbingArchiveRepository.java
  src/main/java/plub/plubserver/domain/archive/service/PlubbingArchiveService.java
  src/main/java/plub/plubserver/domain/feed/model/PlubbingFeedImage.java
  src/main/java/plub/plubserver/domain/notification/controller/NotificationController.java
  src/main/java/plub/plubserver/domain/notification/dto/NotificationDto.java
  src/main/java/plub/plubserver/domain/notification/model/Notification.java
  src/main/java/plub/plubserver/domain/notification/service/NotificationService.java
Labels: 기능

#41 [PLUB-136] Static Response Controller 제작 (투두리스트, 일정)
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/calendar/controller/PlubbingCalendarController.java
  src/main/java/plub/plubserver/domain/calendar/dto/PlubbingCalendarAttendDto.java
  src/main/java/plub/plubserver/domain/calendar/dto/PlubbingCalendarDto.java
  src/main/java/plub/plubserver/domain/calendar/model/AttendStatus.java
  src/main/java/plub/plubserver/domain/calendar/model/PlubbingCalendar.java
  src/main/java/plub/plubserver/domain/calendar/model/PlubbingCalendarAttend.java
  src/main/java/plub/plubserver/domain/calendar/repository/PlubbingCalendarRepository.java
  src/main/java/plub/plubserver/domain/calendar/service/PlubbingCalendarService.java
  src/main/java/plub/plubserver/domain/plubbing/model/Plubbing.java
  src/main/java/plub/plubserver/domain/plubbing/model/PlubbingDate.java
  src/main/java/plub/plubserver/domain/timeline/model/PlubbingTimeline.java
  src/main/java/plub/plubserver/domain/timeline/repository/PlubbingTimelineRepository.java
  src/main/java/plub/plubserver/domain/todo/controller/PlubbingTodoController.java
  src/main/java/plub/plubserver/domain/todo/dto/PlubbingTodoDto.java
  src/main/java/plub/plubserver/domain/todo/model/PlubbingTodo.java
  src/main/java/plub/plubserver/domain/todo/repository/PlubbingTodoRepository.java
  src/main/java/plub/plubserver/domain/todo/service/PlubbingTodoService.java
Labels: 기능
