Repository PLUB2022/PLUB-Server, pull requests merged in 2023-04, with the labels that each got.

#74 [PLUB-194] 모집 지원서 수정 API, 알림 수신 여부 변경 API
  src/main/java/plub/plubserver/domain/account/controller/AccountController.java
  src/main/java/plub/plubserver/domain/account/dto/AccountDto.java
  src/main/java/plub/plubserver/domain/account/dto/AuthDto.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
  src/main/java/plub/plubserver/domain/feed/service/FeedService.java
  src/main/java/plub/plubserver/domain/notification/service/NotificationService.java
  src/main/java/plub/plubserver/domain/plubbing/dto/PlubbingDto.java
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/dto/RecruitDto.java
  src/main/java/plub/plubserver/domain/recruit/model/AppliedAccount.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
Labels: 기능

#75 [PLUB-192] 신고 통합 및 회원 정지 API
  src/main/java/plub/plubserver/common/exception/StatusCode.java
  src/main/java/plub/plubserver/config/jwt/JwtProvider.java
  src/main/java/plub/plubserver/domain/account/controller/AccountController.java
  src/main/java/plub/plubserver/domain/account/dto/AccountDto.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/model/AccountStatus.java
  src/main/java/plub/plubserver/domain/account/model/SuspendAccount.java
  src/main/java/plub/plubserver/domain/account/repository/SuspendAccountRepository.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
  src/main/java/plub/plubserver/domain/account/service/AuthService.java
  src/main/java/plub/plubserver/domain/archive/controller/ArchiveController.java
  src/main/java/plub/plubserver/domain/archive/service/ArchiveService.java
  src/main/java/plub/plubserver/domain/notification/controller/NotificationController.java
  src/main/java/plub/plubserver/domain/notification/service/NotificationService.java
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/main/java/plub/plubserver/domain/report/config/ReportConstant.java
  src/main/java/plub/plubserver/domain/report/config/ReportMessage.java
  src/main/java/plub/plubserver/domain/report/config/ReportStatusMessage.java
  src/main/java/plub/plubserver/domain/report/controller/ReportController.java
  src/main/java/plub/plubserver/domain/report/dto/ReportDto.java
  src/main/java/plub/plubserver/domain/report/model/Report.java
  src/main/java/plub/plubserver/domain/report/model/ReportTarget.java
  src/main/java/plub/plubserver/domain/report/repositoy/ReportRepository.java
  src/main/java/plub/plubserver/domain/report/service/ReportService.java
  src/main/java/plub/plubserver/domain/test/TestController.java
Labels: 기능, 리팩토링

#77 [PLUB-200] 닉네임 변경 횟수 제한
  src/main/java/plub/plubserver/common/constant/GlobalConstants.java
  src/main/java/plub/plubserver/common/exception/StatusCode.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/model/AccountNicknameHistory.java
  src/main/java/plub/plubserver/domain/account/repository/AccountNicknameHistoryRepository.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
  src/main/java/plub/plubserver/domain/report/service/ReportService.java
Labels: 😎 Feature, 🛠️ Refactoring
