Repository PLUB2022/PLUB-Server, pull requests merged in 2023-03, with the labels that each got.

#63 [PLUB-169] 게시판 커서 기반 페이징으로 개선
  src/main/java/plub/plubserver/domain/feed/controller/FeedController.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedCommentRepositoryCustom.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedCommentRepositoryImpl.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedRepositoryCustom.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedRepositoryImpl.java
  src/main/java/plub/plubserver/domain/feed/service/FeedService.java
  src/main/java/plub/plubserver/util/CursorUtils.java
Labels: 리팩토링

#64 [PLUB-172] 투두 커서 업데이트 및 기능 추가(좋아요, 작성자)
  src/main/java/plub/plubserver/common/exception/StatusCode.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/todo/controller/TodoController.java
  src/main/java/plub/plubserver/domain/todo/dto/TodoDto.java
  src/main/java/plub/plubserver/domain/todo/model/Todo.java
  src/main/java/plub/plubserver/domain/todo/model/TodoLike.java
  src/main/java/plub/plubserver/domain/todo/model/TodoTimeline.java
  src/main/java/plub/plubserver/domain/todo/repository/TodoLikeRepository.java
  src/main/java/plub/plubserver/domain/todo/repository/TodoTimelineRepository.java
  src/main/java/plub/plubserver/domain/todo/repository/TodoTimelineRepositoryCustom.java
  src/main/java/plub/plubserver/domain/todo/repository/TodoTimelineRepositoryImpl.java
  src/main/java/plub/plubserver/domain/todo/service/TodoService.java
Labels: 기능, 리팩토링

#65 [PLUB-178] 일정 권한 기능 수정
  src/main/java/plub/plubserver/common/exception/StatusCode.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/calendar/dto/CalendarDto.java
  src/main/java/plub/plubserver/domain/calendar/model/Calendar.java
  src/main/java/plub/plubserver/domain/calendar/service/CalendarService.java
Labels: 기능, 리팩토링

#66 [PLUB-174] 모집글 검색, 북마크 검색 커서 전환
  src/main/java/plub/plubserver/domain/recruit/controller/RecruitController.java
  src/main/java/plub/plubserver/domain/recruit/dto/RecruitDto.java
  src/main/java/plub/plubserver/domain/recruit/repository/BookmarkRepository.java
  src/main/java/plub/plubserver/domain/recruit/repository/BookmarkRepositoryCustom.java
  src/main/java/plub/plubserver/domain/recruit/repository/BookmarkRepositoryImpl.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepositoryCustom.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepositoryImpl.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/main/java/plub/plubserver/domain/test/TestController.java
  src/main/java/plub/plubserver/domain/test/TestDto.java
Labels: 리팩토링

#67 [PLUB-174] 공지사항, 공지사항 댓글 개선
  src/main/java/plub/plubserver/common/dummy/NoticeDummy.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedCommentRepositoryImpl.java
  src/main/java/plub/plubserver/domain/feed/repository/FeedRepository.java
  src/main/java/plub/plubserver/domain/feed/service/FeedService.java
  src/main/java/plub/plubserver/domain/notice/controller/NoticeController.java
  src/main/java/plub/plubserver/domain/notice/dto/NoticeDto.java
  src/main/java/plub/plubserver/domain/notice/model/Notice.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeCommentRepository.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeCommentRepositoryCustom.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeCommentRepositoryImpl.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeLikeRepository.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeRepository.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeRepositoryCustom.java
  src/main/java/plub/plubserver/domain/notice/repository/NoticeRepositoryImpl.java
  src/main/java/plub/plubserver/domain/notice/service/NoticeService.java
Labels: 기능, 리팩토링

#68 [PLUB-183] CD 파이프라인 리펙토링
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/plub/plubserver/config/JasyptConfig.java
  src/main/resources/application.yml
Labels: 리팩토링

#69 [PLUB-185] 알림 API 추가 및 스펙 수정
  src/main/java/plub/plubserver/common/exception/StatusCode.java
  src/main/java/plub/plubserver/domain/calendar/service/CalendarService.java
  src/main/java/plub/plubserver/domain/feed/service/FeedService.java
  src/main/java/plub/plubserver/domain/notice/service/NoticeService.java
  src/main/java/plub/plubserver/domain/notification/aop/NotifyAspect.java
  src/main/java/plub/plubserver/domain/notification/controller/NotificationController.java
  src/main/java/plub/plubserver/domain/notification/dto/NotificationDto.java
  src/main/java/plub/plubserver/domain/notification/model/Notification.java
  src/main/java/plub/plubserver/domain/notification/model/NotificationType.java
  src/main/java/plub/plubserver/domain/notification/service/NotificationService.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/service/RecruitService.java
  src/main/java/plub/plubserver/domain/report/service/ReportService.java
  src/main/java/plub/plubserver/domain/test/TestController.java
  src/test/java/plub/plubserver/domain/calendar/CalendarMockUtils.java
  src/test/java/plub/plubserver/domain/calendar/CalendarServiceTest.java
  src/test/java/plub/plubserver/domain/recruit/RecruitServiceTest.java
Labels: 기능

#70 [PLUB-187] 회원 전체 조회 및 검색
  src/main/java/plub/plubserver/domain/account/controller/AccountController.java
  src/main/java/plub/plubserver/domain/account/dto/AccountDto.java
  src/main/java/plub/plubserver/domain/account/dto/AuthDto.java
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/account/model/AccountStatus.java
  src/main/java/plub/plubserver/domain/account/repository/AccountRepository.java
  src/main/java/plub/plubserver/domain/account/repository/AccountRepositoryCustom.java
  src/main/java/plub/plubserver/domain/account/repository/AccountRepositoryImpl.java
  src/main/java/plub/plubserver/domain/account/service/AccountService.java
Labels: 기능

#71 [PLUB-167] 일정 스케줄러 추가
  src/main/java/plub/plubserver/domain/calendar/config/SchedulerConfig.java
  src/main/java/plub/plubserver/domain/calendar/model/CalendarAlarmType.java
  src/main/java/plub/plubserver/domain/calendar/service/CalendarService.java
  src/main/java/plub/plubserver/domain/calendar/service/SchedulerService.java
  src/main/java/plub/plubserver/util/CronExpressionGenerator.java
Labels: 기능

#72 [PLUB-188] 알림 기능 추가
  src/main/java/plub/plubserver/domain/account/model/Account.java
  src/main/java/plub/plubserver/domain/notification/dto/FcmDto.java
  src/main/java/plub/plubserver/domain/notification/model/NotificationType.java
  src/main/java/plub/plubserver/domain/notification/service/FcmService.java
  src/main/java/plub/plubserver/domain/notification/service/NotificationService.java
  src/main/java/plub/plubserver/domain/report/service/ReportService.java
  src/main/java/plub/plubserver/domain/test/TestController.java
Labels: 기능

#73 [PLUB-182] 홈 화면 모임 추천 커서 기반 페이징 처리
  src/main/java/plub/plubserver/domain/plubbing/controller/PlubbingController.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepository.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryCustom.java
  src/main/java/plub/plubserver/domain/plubbing/repository/PlubbingRepositoryImpl.java
  src/main/java/plub/plubserver/domain/plubbing/service/PlubbingService.java
  src/main/java/plub/plubserver/domain/recruit/repository/RecruitRepositoryImpl.java
Labels: 기능, 리팩토링
